### ISSUE TITLE
Deadlock if server kills the transfer

### ISSUE THREAD

**Issue by us3r64** [pkg/sftp#181]
If the sftp server is killed on the server side looks to be a deadlock.
To reproduce this start downloading a big file and kill the running `sftp-server` on the server:

```
ps faux | grep "sftp-server"
kill -9 <pid>
```

This looks to happen in `dispatchRequest` and `broadcastErr`

```
goroutine 20 [chan send, 2 minutes]:
github.com/pkg/sftp.(*clientConn).dispatchRequest(0xc4200180c0, 0xc420018780, 0x1384cc0, 0xc42052e0c0)
	/Users/user64/gocode/src/github.com/pkg/sftp/conn.go:110 +0x1f3
github.com/pkg/sftp.(*File).WriteTo.func1(0xc42023c000, 0x8000, 0x8000, 0x868000)
	/Users/user64/gocode/src/github.com/pkg/sftp/client.go:771 +0x10d
github.com/pkg/sftp.(*File).WriteTo(0xc42001c660, 0x13837c0, 0x13c27a0, 0x31a00f0, 0xc42001c660, 0xc420063501)
	/Users/user64/gocode/src/github.com/pkg/sftp/client.go:781 +0xae8
io.copyBuffer(0x13837c0, 0x13c27a0, 0x1382940, 0xc42001c660, 0x0, 0x0, 0x0, 0xc420049ce0, 0xc420049cd8, 0xc4200143c0)
	/usr/local/opt/go/libexec/src/io/io.go:380 +0x31a
io.Copy(0x13837c0, 0x13c27a0, 0x1382940, 0xc42001c660, 0x0, 0x0, 0x554)
	/usr/local/opt/go/libexec/src/io/io.go:360 +0x68

goroutine 5 [chan send, 2 minutes]:
github.com/pkg/sftp.(*clientConn).broadcastErr(0xc4200180c0, 0x13828c0, 0xc420070020)
	/Users/user64/gocode/src/github.com/pkg/sftp/conn.go:123 +0x272
github.com/pkg/sftp.(*clientConn).loop(0xc4200180c0)
	/Users/user64/gocode/src/github.com/pkg/sftp/conn.go:51 +0x92
created by github.com/pkg/sftp.NewClientPipe
	/Users/user64/gocode/src/github.com/pkg/sftp/client.go:77 +0x20c

```

**Comment by eikenb** [comment]
Thanks for the report. I've reproduced the issue and will look into it. If you do as well, please pass along any discoveries.

**Comment by eikenb** [comment]
Figured out the problem and might have a fix.

The problem is that broadcastErr() loops over all current inflight requsts and sends an error down the channel they have a reference to. The reading side of that channel is in a loop that calls dispatchRequest() multiple times based on desiredInFlight. If an error handles in that method it immediately sends that error down the channel. But it doesn't break out of the loop, so it would call more dispactRequests() which would do the same. 

At the same time the broadcastErr() was triggered deu to an "unexpected EOF" error from the suddenly closed socket. It loops through all inFlight requests and sends the error down the channel (same channel that dispatchRequest is using above).

The broardcastErr() messages fill up the channel during the while the loop running the dispatchRequest() calls is going on. So when the dispatchRequest() tries to send an error it is blocked by the full channel. That blocking means it never moves past that part of the main loop to where it actually reads from the channel. Thus a deadlock.

2 possible solutions.

1) Set the channel size to the maxConcurrentRequests. This would mean the channel would be big enough to hold all the errors from broadcastErr() and the dispatchRequest() errors so it could make it to the channel reading code.

2) Run the dispatchRequest() call in a goroutine. This makes it so the dispatchRequest() calls don't block the main  loop so the code would move on to the point of reading from the channel.

Both changes prevent the deadlock. Both changes pass all the tests.

Anyone have any thoughts one which is the better solution?

**Comment by us3r64** [comment]
What I'm doing is call the dispatchRequest and broadcastErr ch write as a goroutine:

```
go func() { ch <- result{err: err} }()
```

**Comment by eikenb** [comment]
That's similar to my solution of running the dispatchRequest() call in a goroutine. Just running it in the goroutine is enough as the blocking write to the channel in it is what is preventing the loop from reaching the channel read.

In my code I added the goroutine to client.go line 766. Changing it to...

    go f.c.dispatchRequest(ch, sshFxpReadPacket{

And that was enough to fix it. The other fix was changing client.go line751 to...

    ch := make(chan result, maxConcurrentRequests)

I'm thinking I like the first one a bit better at this point but I haven't made up my mind 100% just yet.

Thanks for the feedback.

**Comment by eikenb** [comment]
Note that this is going to be a problem in all 4 read/write methods (Read, WriteTo, Write, ReadFrom) as they all use the same pattern.

Looking at using the go dispatchRequest() on each of these, it won't work on ReadFrom() due to it re-using a []byte for the reader. Creating a new []byte for each request causes a significant slowdown in throughput. So the options are doing something more like @us3r64 did and just putting dispatchRequest's error channel send in a goroutine or using the large channel buffer.

**Comment by eikenb** [comment]
I think I've decided to go with the bigger buffer. The channel is already buffered, so increasing the size doesn't really add any cognitive load and doesn't really add significantly to the resource usage. And having just the channel write in a go-routine seems like a hack.
