### ISSUE TITLE
Expanding the Filereader and Filewriter interface

### ISSUE THREAD

**Issue by vansante** [pkg/sftp#201]
Hello,

I have been looking at adding SFTP support to our project and the request-interface looks very nice and clean for implementing that. The only thing we are running into is a lack of a signal when the file reader/writer is done and the client is done writing/reading. We need to know this, because we make use of internal locking on files, and we cannot release the lock without this signal.

One way of doing this would be to expand the interfaces with these two methods:
`Filereadfinish(r *Request) (err error)`
`Filewritefinish(r *Request) (err error)`
and adding the file handle identifier to the Request struct to keep track of which file reader/writer is finished.

However I can imagine you don't like expanding the interface as it breaks backwards compatibility. Another option would be to add a property/method on the Request struct to add a callback function that would be called whenever the reading/writing is done. This is a nonbreaking interface change and would thus probably be preferred.

Is this a feature you are willing to add? (Of course I am willing to contribute a PR :) )

**Comment by puellanivis** [comment]
If the ReaderAt or WriterAt implement io.Closer, then this Close() function will be called.

So, in order to support your use case, your Filereader and Filewriter should return a value that also implements io.Closer, and in this Close receiver method, you can then know when the client is finished using that file, and the file lock may be released.

**Comment by vansante** [comment]
While this is true I find it sort of counter intuitive because the Fileread() function in the interface does not even suggest that the request-server will close the stream if it implements the Close() function. I also kind of dislike the fact that it relies on a reflection check rather than being a formal feature. (By changing the type declaration in the Fileread and Filewrite interface to a superinterface containing both ReaderAt/WriterAt and Closer).

To conclude Id rather see a more formal way of doing this, but we'll probably end up implementing it the way you suggested if the api does not change.

**Comment by puellanivis** [comment]
While I understand the appearance of being counter-intuitive, the API, as is, is pretty common as a design in Go. The case of “I would rather not have to wrap everything in a NopCloser just to get it to pass through an interface…” is pretty big.

The idea in Go is to keep interfaces small, not cluttered. The “bare minimum” of required interface should be used. In particular, tacking things together until you have a `io.ReadAtWriteAtSeekFlushCloser` is not good design.

Meanwhile, it is easy to note in documentation, “if this implements io.Closer, then this library will call the Close receiver after the client has stopped using the file.”

So, I think the correct answer here would be to document that the pkg/sftp library will call Close on the returned io.ReaderAt if it is implemented.

**Comment by puellanivis** [comment]
PS: in particular, io.Copy only takes io.Reader and io.Writer, but if either implements a WriteTo, or ReadFrom, it will use that, rather than generic logic reading into a buffer and writing out to the other.

This allows, for instance, the bytes.Buffer to just straight up io.Writer.Write(bytes.Buffer.Bytes()) without having to do any additional buffering of the already buffered data.

**Comment by vansante** [comment]
Okay, fair enough. We'll use the API as is then. Thanks for the clarification.
