### ISSUE TITLE
Use a virtual filesystem abstraction for Requests interface?

### ISSUE THREAD

**Issue by crazed** [pkg/sftp#205]
I was looking into what was necessary to map my internal service calls to the `sftp.Handlers` struct methods and found myself wanting a filesystem-like abstraction. I wound up with something along the lines of:

```
type vfs interface {
	Mkdir(path string) error
	Open(path string) (*fileBuffer, error)
	Stat(path string) (os.FileInfo, error)
	List(prefix string) []os.FileInfo
}
```

Then the `sftp.Handlers` methods looked a bit like:

```
// Filewrite implements sftp.FileWriter.
func (v *handler) Filewrite(req *sftp.Request) (io.WriterAt, error) {
	v.vfsMu.Lock()
	defer v.vfsMu.Unlock()
	return v.vfs.Open(req.Filepath)
}

// Filelist implements sftp.FileLister.
func (v *handler) Filelist(req *sftp.Request) (sftp.ListerAt, error) {
	v.vfsMu.Lock()
	defer v.vfsMu.Unlock()

	// There's more than one method passed on to the Filelist method.
	switch req.Method {
	case "List":
		// List means actual list everything in the directory
		list := v.vfs.List(req.Filepath)
		return listerat(list), nil
	case "Stat":
		// Stat actually means just do a stat on the provided path
		stat, err := v.vfs.Stat(req.Filepath)
		if err != nil {
			return nil, err
		}
		return listerat([]os.FileInfo{stat}), nil
	case "Readlink":
		// Readlink is for symlinks, but we don't support this.
		return nil, os.ErrPermission
	}
	return nil, nil
}
```

What do you think about this type of abstraction? I used these for inspiration:

https://godoc.org/golang.org/x/tools/godoc/vfs
https://github.com/blang/vfs

In my opinion this type of interface would allow users of this package to worry less about sftp protocol details and think more about mimicking a filesystem (which is kinda what sftp itself does).

**Comment by eikenb** [comment]
@crazed  .. Just noticed this post and I'll try to address it soon. My current work has me pretty occupied with something not really related to this (sftp/go). I'll be done with it soon and be getting back to working on this and so will be in the mindset to have a better opinion on this. Just wanted to let you know I was aware of your question and will get back to you.

**Comment by eikenb** [comment]
As a bit of background, in earlier discussions about providing an abstracted back-end interface Dave specifically said he did _not_ want yet another VFS implementation. See issue #95 for some of the discussion.

This is why I approached the Handlers as I did, working from a more event/action based interface vs  trying to represent a filesystem. More specifically I focused on the return values, grouping things that have common return types. This lead to the smallest interface of the ones I had tested and I liked the simplicity of it. Also I found that this system maps better to non-filesystem backends like S3 and an VFS does.

I'm not sure if you were suggesting we adopt this instead of the current one, but if you were then I'm afraid I'm not interested. I'm pretty happy with the current abstraction and plan to keep it for now.

You could of course use a VFS abstraction on top of the Handlers interfaces, which it sounds like is what you are doing. If this ends up being nice and you are able to publish it I'd love to see it.

**Comment by crazed** [comment]
Makes sense, yeah I mean I'll see what it winds up looking like. Thanks for the reply!
