### ISSUE TITLE
 Failed to send packet header: EOF

### ISSUE THREAD

**Issue by yudao** [pkg/sftp#211]
Hi!

I'm facing off an inexplicable error.

I need to add sftp to my storage interface. I can connect to it but when I'm trying to do anything on my sftp server, I always receive the same error :  

> Failed to send packet header: EOF.

I've created a gist with my source file, my test file (which each function return this same error) and the particular configuration of my sshd.

https://gist.github.com/anonymous/95c89bb32e4d8341f8f099a5d0f5b0a0

If someone could help me, I've tried a lot of things. I've seen an issue with this error but when someone need to copy large file.

Thanks a lot.

Yu.

**Comment by eikenb** [comment]
The example code in the gist fails to work with those EOF errors due to the fact that you are trying to use closed connections. In your Sftp.connect() method you defer closing the ssh client and sftp session. Those defers run when the connect() method exits... so connect() is returning a closed sftp client session.

If you simply comment out the 2 defer statements in connect() it will work.

**Comment by yudao** [comment]
@eikenb Thx a lot! Sorry for the inconvenience.
