### ISSUE TITLE
context.Context for request lifecycle?

### ISSUE THREAD

**Issue by crazed** [pkg/sftp#222]
I have some async calls that are made during various handlers, and at the moment I just have to throw a timeout context around them. It would be nice if there was a cancellable context attached to the handlers that is cancelled once the request closes. Looking through the code I think it could be done, but would need to add handlers that accept a context as the first argument. Is this something that makes sense for SFTP requests?

**Comment by puellanivis** [comment]
Absolutely, but the model right now was modeled I think around the standard http library, which unfortunately lacks this sort of context.Context use, and which… well, due to Golang v1.0 promise is unlikely to ever find much traction. :(

That is not to say that _this_ package could not change, but the idea because many of the pkg packages is that they would mimic a lot of the standard library’s ideas of not introducing any breaking changes.

**Comment by crazed** [comment]
The http standard library added to the request method the ability to retrieve a context and set one via:

https://golang.org/pkg/net/http/#Request.WithContext
https://golang.org/pkg/net/http/#Request.Context

I wonder if we could do something similar in the sftp package?

**Comment by puellanivis** [comment]
Sounds like a decent idea, not sure if many people have coding time for it though.

**Comment by eikenb** [comment]
I'm moving back here as I'm looking to talk more about the design in general, without referencing the code in the PR specifically.

> Looking through the code I think it could be done, but would need to add handlers that accept a context as the first argument.

Why did you think you'd need to change the handler signatures? What if the Context was a private field on the Request object set/fetched via the WithContext/Context methods. The initial Context would be created in the factory method and things would go from there. If we made sure Request.close() was called in every case, we could be sure the resources were freed appropriately.

**Comment by puellanivis** [comment]
> Why did you think you'd need to change the handler signatures?

I think this is due to the concept in Go that context.Context should always be passed explicitly…

I know at least internally at Google, the http.Handler signature contains the context.Context as the first argument. It is merely an artifact of the Go 1 compatibility promise that prevents that signature from changing in the standard library. (Some might argue that ideally, it should change, but by other definitions of ideal, the Go 1 compatibility promise is far more important.)

**Comment by crazed** [comment]
> Why did you think you'd need to change the handler signatures? What if the Context was a private field on the Request object set/fetched via the WithContext/Context methods. The initial Context would be created in the factory method and things would go from there. If we made sure Request.close() was called in every case, we could be sure the resources were freed appropriately.

Yeah that was my initial assumption until I remembered http's Request struct has the `WithContext/`Context` methods. I think putting it on the Request w/ the cancel method is fine as long as the close method does get called in every case.

**Comment by eikenb** [comment]
I've pulled down your PR to a local branch where I will rework it. I'll push the branch and create a new PR for it  so that you both may review/comment on it if you'd like.

I'm going to make a some tweaks to your initial commit but leave it in your name to give you credit, then build on that. If you don't want me to do that just let me know.

**Comment by puellanivis** [comment]
😭 I just realized so much sads while looking over the code… we need to ensure that any CancelFuncs made get called… :( it’s not enough to ask that each Request be Closed(), we need _each_ Request to be Closed()… even the one that was from NewRequest(), which was likely replaced by WithContext() (if it be called.)

**Comment by eikenb** [comment]
By moving the context creation out of the public NewRequest we can get a default one in place that would always be handled/closed by the server code.

Alternatively the default context could be the empty context.Backgroud context. But this doesn't seem overly useful and the net.http server code sets a context.WithCancel on the request, so this is more in line with that.

I also realize there isn't any means for the user to cancel the request/context. It only happens when the request is closed. This seems OK to me as what I understand to be the use case is when an async process is launched it needs to know when to stop. It would monitor the context for the cancel, while the cancel would be triggered by the main handler returning an error or what-not and trigger the close.

**Comment by puellanivis** [comment]
Well, yeah, if the user wants to close the context themselves, they need to wrap it in a WithCancel context.

My concern is that the expected use case of WithContext would be dropping context.CancelFuncs on the floor without calling them. As a result, there would be at least a memory leak, but also as likely a goroutine leak.

My point is: if we make a context.CancelFunc it has to be called to release the resources. Removing all references to the CancelFunc and letting it be “garbage collected” won’t work alone… We have to ensure that the CancelFunc is called at some point.

`go vet` even warns about this sort of thing.

**Comment by eikenb** [comment]
@crazed What do you think of the CancelFunc only being called automatically by the underlying server code as part of the request finalization/close? To trigger the CancelFunc call earlier than normal you would return an error from your handler, otherwise it would just happened normally upon completion of the request.

Does this work for you? Or is there some case that you would need to manually call the CancelFunc? If so, could you describe it?

Thanks.

**Comment by eikenb** [comment]
@puellanivis So the main downside is that this adds the requirement to the server code that the Request object is always closed. This does add a bit of complexity/fragility.

The other option would be to not set it or set it to the empty context from context.Background. In this case it'd be up to the user to use WithContext to set their own context and if they use WithCancel they'd be responsible for calling it. That would probably be my default stance as it is more neutral except for the fact that the standard library uses WithCancel by default (I mean in the server code). I haven't written much backend HTTP code since it was added so I haven't gotten a good feel for it and so am inclined to follow the standard lib.

**Comment by crazed** [comment]
> @crazed What do you think of the CancelFunc only being called automatically by the underlying server code as part of the request finalization/close? To trigger the CancelFunc call earlier than normal you would return an error from your handler, otherwise it would just happened normally upon completion of the request.

Yeah this sounds fine with me from the server side. Honestly I just want to take the context and use it, possibly creating a child context, to allow downstream requests to get cancelled if the SFTP client closes their connection to my server. 

I don't think I would ever want to change the context associated with a request from the server side, but it does make sense on the client side to assign your own context.

**Comment by puellanivis** [comment]
Server side it makes tons of sense to setup the WithCancel and arrange for it to be called. But if a client calls NewRequest then makes a WithContext call, then the old CancelFunc from the NewRequest still needs to be called at some point.

So, from the server-side I don’t think anything is wrong. I’m just concerned about someone calling the NewRequest then using WithContext to replace the context, then their code will have a hanging CancelFunc.

**Comment by eikenb** [comment]
> But if a client calls NewRequest then makes a WithContext call [..]

The client code doesn't use Request objects anywhere. If for some reason someone did, they would be in the client code and so the default server session Request would not be created nor would its context.

> I’m just concerned about someone calling the NewRequest then using WithContext to replace the context, then their code will have a hanging CancelFunc.

If they call NewRequest and add a WithCancel context to it, then it would be up to them to cancel it. The server Request would still get closed by the server code w/ its local reference to it. They can't replace that reference.

**Comment by ernesto-jimenez** [comment]
> But if a client calls NewRequest then makes a WithContext call, then the old CancelFunc from the NewRequest still needs to be called at some point.

In that case there wouldn't be an old `CancelFunc`.

On the client side, my expectation would be that `NewRequest`'s underlying context is `context.Background()`, which cannot be cancelled.

If I were to do:
```go
ctx, cancel := context.WithTimeout(req.Context(), 3 * time.Second)
req = req.WithContext(ctx)
```

It is my responsibility to call `cancel`. Not `sftp`'s.

**Comment by puellanivis** [comment]
Indeed, the point being made was in relation to an earlier version where in the NewRequest automatically created a `context.WithCancel(context.Background())`. That codepath no longer existing makes my entire line of worry completely irrelevant now. ;)
