### ISSUE TITLE
How do I access the binary file data within my RequestServer Handlers

### ISSUE THREAD

**Issue by felixbecker** [pkg/sftp#267]
Hi, 

I hope this is the right place to ask this question above. 
I am trying to use the sftp server as a facade to backup files to S3. As I was reading through the issues this is what some of you guys also tried to do. 

What I did is, I took the example of the request-server and implemented a the Handler struct with the interfaces thats needs to be satisfied. I looked at the `sftp.InMemHandler()` to get an inspiration.

The question is, where can I find the binary data of the file when using my custom handler since it is not exposed by `Request`-struct. Especially for `FilePut`- the file that gets uploaded to the sftp server.

I was hoping that I could use the hook functions 	`FileGet` ,`FilePut`,`FileCmd`,`FileList` and work here with the aws-sdk and map it back to FileInfos. The idea ist basically to have not an in-memory list or whatsoever.

Any tipps, tricks and feedback would be greatly appreciated.

**Comment by eikenb** [comment]
Hey Felix,

I wrote the Request based backend specifically because I needed an SFTP server that used S3 as its backend. I have a version working, but haven't been allowed to release it as free software (maybe in the future). So yes, it can do what you want.

Using those 4 hook/handler functions you should be able to replicate most aspects of a filesystem type backed server. FileGet and FilePut are for uploading/downloading, FileCmd is for success/fail type commands and FileList are for anything giving back file info (list, stat, etc).

FileGet and FilePut both work by returning an IO object to read/write the file contents to. You get the path of the file from the Request.Filepath attribute. FilePut takes a FileWriter interface object. The FileWriter interface is documented here: https://godoc.org/github.com/pkg/sftp#FileWriter

Basically that `Filewrite` method takes a Request object as the argument, returns an io.WriterAt (or an error). The data from file the client uploaded will get written to that io.WriterAt object (a series of WriteAt calls). When done assert to see if it matches the io.Closer interface and  call Close() if it can. So basically your job writing the Filewrite() method is to do whatever you need so that you can return an object that supports io.WriteAt.

For mine I use https://godoc.org/github.com/eikenb/pipeat, a version of io.Pipe that supports ReadAt and WriteAt. It keeps my glue code pretty simple, a simplified (untested) version looking something like...

`
func (fs *S3FS) filewrite(r *sftp.Request) (io.WriterAt, error) {
	client := fs.aws.newUploader(fs.sess) // wraps s3manager.NewUploader
	key := fs.getKey(r.Filepath) // converts relative filepath to S3 key
	rdr, wtr, err := pipeat.Pipe()
	if err == nil {
		input := &s3manager.UploadInput{
			Body:                 rdr,
			Bucket:               aws.String(bucket),
			Key:                  aws.String(key),
		}
		go func() {
			output, oerr := client.UploadWithContext(r.Context(), input)
			rdr.CloseWithError(errorMap(oerr))
		}()
	}
	return wtr, errorMap(err)
}
`

Let me know if you have any other questions. I know the documentation is currently lacking and hope to get time to fix that at some point.

**Comment by eikenb** [comment]
Things like this should be added to the documentation; #247

**Comment by felixbecker** [comment]
Hi @eikenb, thank you very much for you reply and the example code.

Based on reading through the issues before I was expecting another api. Especially reading @davecheney comment here: https://github.com/pkg/sftp/issues/95#issuecomment-219582979
I was expecting more something like the ´http.Handler´ 

quoted:
``` sftp.Serve(path, handlerFunc()) ```

so something that passed the file as a io.Reader and an io.Writer for the Response. So the handler func would basically be a middleware. The standard implementation would come with a writer that automatically store to the disc but you could override it. But anyway... now I do understand at a little better - and it is kind of that way but with a different interface. I was especially confused by ReaderAt and ListerAt.

I do also have additional questions:
I there a reason why Handlers is a struct and not an interface?
https://github.com/pkg/sftp/blob/master/request-server.go#L18-L24
```
type Handlers struct {
	FileGet  FileReader
	FilePut  FileWriter
	FileCmd  FileCmder
	FileList FileLister
}
```

And one protocol related question:
whether I use 'ls', 'dir', 'ls -la', I always hit the `r.Method="Stat"` was hit. How would one trigger the `List` request method and what is it used for?

Thanks again for your answers and sorry for asking such newbee questions.

**Comment by eikenb** [comment]
Sorry for the delayed response. Life got busy.

> I there a reason why Handlers is a struct and not an interface?

It is a struct of different interfaces. Feasibly it could have been done as one big interface, but it seemed better to break things into their separate interfaces. With interfaces smaller is almost always better.

> whether I use 'ls', 'dir', 'ls -la', I always hit the r.Method="Stat" was hit. How would one trigger the List request method and what is it used for?

The r.Method set is based on the sftp packet received. You can see the lookup table [in request.go](https://github.com/pkg/sftp/blob/08de04f133f27844173471167014e1a753655ac8/request.go#L347). In that you will see the "List" method gets set when it receives a Readdir packet vs "Stat" method being set for "Stat", "Lstat", and "Fstat" packets. 

So the Method value set will depend on the client you are using. For example OpenSSH's sftp client will send Stat packets if you list an individual file (ls foo) where is sends Readdir if run by itself or on a directory.

**Comment by eikenb** [comment]
Dave's response that you quote was to an earlier, different attempt at creating an extensible backend. I had gone down that path a bit, but found the other example he suggest, inotify's event system, to better fit what I was trying to achieve.
