### ISSUE TITLE
[help] How to upload a directory to sftp server

### ISSUE THREAD

**Issue by ngxlua** [pkg/sftp#273]
hi,

I use the `request-server` in the example to test sftp, but I can't upload the directory, how can I do it, thank you very much

My steps are as follows:

```
cd $GOPATH/src/github.com/pkg/sftp/examples/request-server

go run *.go
```

I use the software `Transmit.app` under `mac` to test, as shown in the figure:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/31426367/45631478-8bb8b480-bacd-11e8-988c-d9c3e1f2a3dc.png">

<img width="442" alt="image" src="https://user-images.githubusercontent.com/31426367/45631490-9410ef80-bacd-11e8-83a4-e4a5a28ffcea.png">

I think maybe the way I used it is wrong, thanks for any possible help.

**Comment by eikenb** [comment]
Did you login? Was there any output from the server?

**Comment by ngxlua** [comment]
@eikenb 

Yes, I am logged in.

```
❯ go run *.go
Listening on [::]:2022
2018/09/17 23:00:11 login detected: testuser
```

I can upload and download a single file, only when uploading multiple files or directories will cause problems.

----

If I don't use the client, the following happens when I use scp. Is it only if I have this?

```
scp -P 2022 Downloads/{3,2} testuser@localhost:/
testuser@localhost's password:
exec request failed on channel 0
lost connection
```

Thanks Reply

**Comment by eikenb** [comment]
Thanks for the reply. I don't have easy access to a mac right now, so a few more questions..

Have you tried with the sftp client included in Openssh? That works for me with the request server example and if it works for you that should mean it is an issue with transmit.app.

Maybe also test transmit.app with examples/sftp-server/ and see if that works. It uses different code and might help indicate some issue specific to the request based server.

Is this the transmit.app you are using: https://www.panic.com/transmit/ ?

Note that `scp` doesn't use the sftp protocol, so that output is expected. The server should reject all ssh connections that don't initiate the sftp subsystem.

Thanks for helping out debugging this issue.

**Comment by ngxlua** [comment]
Thanks, it is my negligence

**Comment by eikenb** [comment]
Great! Glad you figured it out. 

If you think others might hit this issue please consider posting how you solved it/what the actual issue was. Thanks.

**Comment by ngxlua** [comment]
Hello, I just saw your reply.

Under my test, I found that uploading a folder will initiate multiple requests.

I just added a loop to `Accept`, like this

```
for {
		nConn, err := listener.Accept()
		...
}
```

**Comment by eikenb** [comment]
Thanks!

**Comment by eikenb** [comment]
Also... sounds like the client was trying to make multiple connections which the example server wasn't really set up to handle.

**Comment by ngxlua** [comment]
Yes, maybe the example code should be improved.
