### ISSUE TITLE
Wrong value of S_IFMT mask when converting sftp filemode bits to os.FileMode

### ISSUE THREAD

**Issue by cyrilcourvoisier** [pkg/sftp#291]
I encountered this issue when synchronizing a directory using rclone (with sftp) to a server running AIX. Rclone was sending a SSH_FXP_STAT request to test if a directory is, well, a directory.

The STAT request was giving the directory's status as 'not a directory' despite being one.
The problem was in the toFileMode function in attrs.go

```
input filemode bits are                  1 0100 0011 1111 1111‬
syscall.S_IFMT mask bits are             1 1111 0000 0000 0000
```

The different values tested are:

> 

```
 S_IFBLK                                 0 0110 0000 0000 0000
 S_IFCHR                                 0 0010 0000 0000 0000
 S_IFDIR                                 0 0100 0000 0000 0000
 S_IFIFO                                 0 0001 0000 0000 0000
 S_IFLNK                                 0 1010 0000 0000 0000
 S_IFREG                                 0 1000 0000 0000 0000
 S_IFSOCK                                0 1100 0000 0000 0000
```

As you can see, none of the values matchs the input, and the leftmost bit is not used by any value. 
The input would match S_IFDIR if the S_IFMT mask didn't test the leftmost bit.

I have searched the value of S_IFMT mask in other sftp implentations and in the ones I have found, they define S_IFMT as: 1111 0000 0000 0000

for example, the python implementation of stat:
https://github.com/python/cpython/blob/2.7/Lib/stat.py

Or this javascript implementation of sftp:
http://maverick-ng-javadocs.s3-website-eu-west-1.amazonaws.com/constant-values.html#com.sshtools.client.sftp.SftpFileAttributes.S_IFMT

**Comment by puellanivis** [comment]
I’m not sure I see where you are getting the `S_IFMT` is 0x1F000, as a grep of all `go` syscall shows:
```
zerrors_darwin_386.go:	S_IFMT                            = 0xf000
zerrors_darwin_amd64.go:	S_IFMT                            = 0xf000
zerrors_darwin_arm.go:	S_IFMT                      = 0xf000
zerrors_darwin_arm64.go:	S_IFMT                            = 0xf000
zerrors_linux_386.go:	S_IFMT                           = 0xf000
zerrors_linux_amd64.go:	S_IFMT                           = 0xf000
zerrors_linux_arm.go:	S_IFMT                           = 0xf000
zerrors_linux_arm64.go:	S_IFMT                           = 0xf000
zerrors_linux_mips.go:	S_IFMT                           = 0xf000
zerrors_linux_mips64.go:	S_IFMT                           = 0xf000
zerrors_linux_mips64le.go:	S_IFMT                           = 0xf000
zerrors_linux_mipsle.go:	S_IFMT                           = 0xf000
zerrors_linux_ppc64.go:	S_IFMT                           = 0xf000
zerrors_linux_ppc64le.go:	S_IFMT                           = 0xf000
zerrors_linux_s390x.go:	S_IFMT                           = 0xf000
zerrors_netbsd_386.go:	S_IFMT                            = 0xf000
zerrors_netbsd_amd64.go:	S_IFMT                            = 0xf000
zerrors_netbsd_arm.go:	S_IFMT                            = 0xf000
ztypes_openbsd_arm64.go:	S_IFMT   = 0xf000
ztypes_dragonfly_amd64.go:	S_IFMT   = 0xf000
ztypes_openbsd_386.go:	S_IFMT   = 0xf000
ztypes_openbsd_amd64.go:	S_IFMT   = 0xf000
ztypes_solaris_amd64.go:	S_IFMT   = 0xf000
ztypes_freebsd_386.go:	S_IFMT   = 0xf000
ztypes_freebsd_amd64.go:	S_IFMT   = 0xf000
ztypes_freebsd_arm.go:	S_IFMT   = 0xf000
ztypes_openbsd_arm.go:	S_IFMT   = 0xf000
zerrors_aix_ppc64.go:	S_IFMT                        = 0xf000
zerrors_netbsd_arm64.go:	S_IFMT                            = 0xf000
```

Wait, is the client running plan9?
```
errors_plan9.go:	S_IFMT   = 0x1f000
```

**Comment by cyrilcourvoisier** [comment]
No, the client runs Windows 10 ahah

In types_windows, S_IFMT is defined as 0x1f000
https://github.com/golang/go/blob/master/src/cmd/vendor/golang.org/x/sys/windows/types_windows.go

**Comment by puellanivis** [comment]
So, looking through the standards that we target. The SFTP specification we target defines:
> The `permissions' field contains a bit mask of file permissions as defined by posix [1].

And the POSIX standard just defines that `S_IFMT` should exist.
> The <sys/stat.h> header shall define the following symbolic constants for the file types encoded in type mode_t. …
> S_IFMT Type of file.

:woman_shrugging: I’m surprised we never really hit this issue before due to conflicting answers about what `S_IFMT` is defined as. And there’s unfortunately, I do not think any “perfect” universal solution… as Windows/Plan9 could potentially return whatever POSIX permissions that it defined, while the client is stuck assuming it’s own POSIX attributes.

Although, it would seem that all of the Windows `syscall.S_IF…` values match up _except `S_IFMT`.

**Comment by puellanivis** [comment]
Both windows and plan9 versions of these constants contain:
```
	// Invented values to support what package os expects.
```
So, it looks like someone made a typo bringing the code over, and _neither_ of them actually cares about that extra bit.

**Comment by cyrilcourvoisier** [comment]
Yes, it seems that this extra bit is set to 0 most of time. Do you know for what it is used for?

**Comment by puellanivis** [comment]
AIX uses the bit for `S_IFJOURNAL` : https://github.com/golang/go/blob/master/src/syscall/zerrors_aix_ppc64.go#L786

It looks like you found a bug in golang itself, would you like help reporting it?`</clippy>`

**Comment by cyrilcourvoisier** [comment]
Yes, it seems a bug in types_windows.go itself. Ok I will report a bug on https://github.com/golang/go/issues

**Comment by eikenb** [comment]
Hey @cyrilcourvoisier, @puellanivis,

Sorry for not responding earlier, I recently started a new job and have been swamped. Thank you @puellanivis for helping figure out what is going on, I super appreciate your help. As is there doesn't seem to be much for me to do as you to are already on top of things. 

Actually, reading through the golang bug, it looks unsure whether they will fix the issue there or not. So should we consider a workaround for it? Defining our own local S_IFMT that we override on Windows (and maybe Plan9)? I'd happily consider a PR. :)

**Comment by puellanivis** [comment]
Yeah, it looks like we might need to do that. At least temporarily anyways, even if they fix it now, it’s unlikely to get released before the next major point version. 🤷‍♀ A file with the build directive of windows/plan9 defining it ourselves, and then a file with build directive of not windows/plan9 that says “whatever is in syscall.S_IFMT”…

But really, maybe, we might want to force all of the values to be the same on our library? Just scrub those attributes thoroughly, and generate our own values? Seems drastic, but maybe it’s the only way to guarantee compatibility?

**Comment by puellanivis** [comment]
It looks like POSIX has grudgingly defined actual numeric values for the various permission bits of `mode_t` but has not defined definite values for `S_IFMT` and the other `S_IFDIR`, etc. It has since very early included:
> No new S_IFMT symbolic names for the file type values of mode_t will be defined by POSIX.1-XYZ; if new file types are required, they will only be testable through S_ISxx() or S_TYPEISxxx() macros instead. [ref](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_stat.h.html)

Ostensibly, this is an argument that one should be able to use `switch mod & S_IFMT { }` with an exhaustive list of file types, and if none of those match, then you need to call the various `S_ISxyz()` or `S_ISTYPExyz` macros. However, it appears that Go has thrown out that rulebook, and gone aggressively for expanding available `S_IFMT` values: https://golang.org/src/syscall/syscall_js.go#L140

For windows and plan9 we `SHOULD` be able to get them to fix the values (an argument that `S_IFMT` should include no more bits than all defined `S_IFxyz` values inclusive-or'ed together) but now I notice that there's also the `syscall_nacl.go` and `syscall_js.go` that go even further defining S_IFMT with `0370000`. :disappointed: 

It looks strongly like we will always need to have a workaround for buggy implementations, since POSIX has declined to actually define these values, even though every implementation agrees upon their values.

**Comment by eikenb** [comment]
I pushed a PR that addresses the base case here of S_IFMT being wrong on windows and plan9. As windows and plan9 use the same values as all other platforms for the other S_IFxyx values this should fix the reported issue. 

It is simple and ignores the syscall_nacl.go and syscall_js.go thing (what's up with those values?). The former (nacl) I think we can safely ignore as it is deprecated as a platform as of >1.13.  The syscall_js.go values, though weird, do seem internally consistent. So I don't think it will run into this issue.

**Comment by puellanivis** [comment]
😆 maybe, I should have read this before giving review on the PR. 🤷‍♀ oh well.

It’s unfortunately not as simple as making sure that the values are internally consistent, because this is a cross platform value being passed over the wire. It would be nice if the POSIX standard people would actually dictate values for these, since they’re being used in other standards like they are predefined set values via standards, but they’re actually not.

**Comment by eikenb** [comment]
I keep forgetting that it sends the bitmask over the wire... just seems like such an odd practice. I'll add the override for js/wasm as well.

I also looked more closely and realized that the the js/wasm actually has the exact same issue as windows and plan9, it just doesn't use hex notation. In other words, 0000370000 == 0x1f000 and all the other values lack the 1 in the same bitmask position, just like on plan9 and windows. Seems like almost purposeful obfuscation to write it that way when hex notation was used in all other cases.

**Comment by puellanivis** [comment]
Indeed… quite odd. Also, OR–ing all of the possible values on windows and plan9 together, you still end up with 0xf000 🤷‍♀ So, who knows why they added that weird off–bit.
