### ISSUE TITLE
Creating file on AWS SFTP managed services always get "Cannot open file in mode: WRITE|TRUNCATE|CREATE|READ" (SSH_FX_OP_UNSUPPORTED)

### ISSUE THREAD

**Issue by rama3i** [pkg/sftp#305]
When using AWS SFTP managed services, sftp client always failed to create files. Create function (`client.Create()` ) always returned error with message "Cannot open file in mode: WRITE|TRUNCATE|CREATE|READ" (SSH_FX_OP_UNSUPPORTED).

This error only happened on AWS SFTP managed services. Regular SFTP server has no issue. The same endpoint were tested using sftp command, FileZilla and even .Net sftp library and all working normally. Only go sftp package were returned the error.

**Comment by eikenb** [comment]
Hey @rama3i, thanks for the report.

This one is going to be tricky to debug as I don't have access to an AWS account through work at the moment and AWS Transfer is pretty expensive w/ no free tier. So any additional information you can supply would be great. Thanks.

**Comment by rama3i** [comment]
Hi @eikenb ,

I am not really expert on neither Go nor sftp, but can you show me how to provide more info? Is there anything I could do to verbosely log everything to provide you any detail required?

**Comment by sugacube** [comment]
i'm a quite time constrained at the moment so difficult to dive deeply, but I had some thought about it. I could be totally wrong here but maybe worth a shot.

As aws sftp is s3 backed, maybe can't support read/write connection at the same time. maybe client.Create() should only open for writing not for reading ? @rama3i  maybe you could try to change that in the code and try to see if that would work?  (e.g. in client.go function Create() change `os.O_RDWR` into `os.O_WRONLY`) ?

I'm not sure how other sftp clients open for write - i tried looking around in the code of filezilla but could not immediately find relevant code. mabye @eikenb or someone else has looked around in the past in other clients maybe worth checking how this is done in other clients.

other thought I had was aws permissions, but that can't be the reason as apparently other clients work.

**Comment by sugacube** [comment]
just checked source code of winscp. winscp (client) appears afaict when uploading a file to open in mode write/create or write/create/truncate which seems to confirm my suspicion that removing the "READ" permission might solve the issue.

**Comment by eikenb** [comment]
Thanks for the investigation and thoughts @sugacube. I checked openssh's sftp client and it behaves similarly. Opening a new file with either uses write/create/truncate or write/create/append. No read anywhere in the upload call.

@rama3i you can test this idea out by replacing your `client.Create(path)` call with `client.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC)`. This would replicate what winscp and openssh do opening the file for write only. If you get a chance to try this, please let me know if it helps.

**Comment by rama3i** [comment]
Thanks @sugacube @eikenb . The proposed solution works as expected. Using `os.O_WRONLY|os.O_CREATE|os.O_TRUNC` as flag I could create the file on AWS managed SFTP.

Why do this option matters? Will this solution works for regular SFTP? I actually think that the one causing error is the `os.O_RDWR` and `os.O_TRUNC`, and removing two of them leaving for only `os.O_CREATE` should works. Sadly that's not working. That's why I raise this issues.

**Comment by puellanivis** [comment]
> os.Create() opens files using O_RDWR

Wait… what?! :eyes: 

I always just assumed that it was opened in `O_WRONLY` because the `O_CREATE` and `O_TRUNC` flags passed in make its usefulness for reading neigh absent.

**Comment by eikenb** [comment]
@puellanivis ... :rofl: ...  No. They replicated the `os` package directly, including the flags used in file operations. I think they wanted the sftp files to be API compatible with os files. I understand what they were going for.. but am unsure it works well in practice for all cases.

**Comment by puellanivis** [comment]
I mean, it makes sense why this repo duplicated what `os.Create` does, but I never would have thought it would have read permissions.

**Comment by sugacube** [comment]
To me (and you) it may be counter intuitive, but I justs saw it's crystal clear in the docs - it's repeated 3 times :
> `func (c *Client) Create(path string) (*File, error)`
Create creates the named file mode **0666** (before umask), truncating it if it already exists. If successful, methods on the returned File can be **used for I/O**; the associated file descriptor has **mode O_RDWR**. If you need more control over the flags/mode used to open the file see client.OpenFile. 

It's possible (but not very common) for an SFTP server to allow either read or write, but pretty unusual to offer both read and write but not at the same time. This must be a very AWS specific thing.

**Comment by puellanivis** [comment]
I am fairly sure this “feature” of Amazon is a result of quirks of how their s3 buckets work.

**Comment by rama3i** [comment]
> I am fairly sure this “feature” of Amazon is a result of quirks of how their s3 buckets work.

Make sense. Object on S3 bucket allows write and read, but might not both. When we open, it actually download the file, not the actual file open like the one on the OS directly to the path (please pardon my lack of technical terms and knowledge). This might be happened for other SFTP that backed with Object Store, such as Open Stack Object Storage (Swift) and others. AFAIK object store only support Put and Get. So yeah, this might be the reason.

As this is not a common case, I think well documented workaround should be enough. At least developer know if `Create` fails on Object Store backed SFTP, they could use `Open` with `os.O_WRONLY|os.O_CREATE|os.O_TRUNC` flag

**Comment by puellanivis** [comment]
Solving the problem with documentation is not a bad idea. We can add a note under the godoc for `Create` that some backends like AWS SFTP do not support `O_RDWR` which is used by `Create` and provide the quick-workaround to switch to `OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC)` in that case.

**Comment by rama3i** [comment]
Looking at the code, statusError.Code were taken from 32 bit of first data (CMIIW). Changing to int might cause some data lost. I think casting `sftp.ssh_FX_OP_UNSUPPORTED` to uint32 would be safer.

Trying to do the same as @puellanivis did.

``` go
func (c *Client) Create(path string) (*File, error) {
	file,err := c.open(path, flags(os.O_RDWR|os.O_CREATE|os.O_TRUNC))
	// AWS managed SFTP issues workaround. Need to check whether os.ORDWR is supported or not, if not (indicated by
	// error code ssh_FX_OP_UNSUPPORTED) try to reopen using os.O_WRONLY
	statusError, ok := err.(*StatusError)
	if err != nil && ok && statusError.Code == uint32(ssh_FX_OP_UNSUPPORTED){
		return c.open(path, flags(os.O_WRONLY|os.O_CREATE|os.O_TRUNC))
	}
	return file,err
}
```

**Comment by puellanivis** [comment]
I was not writing my failover code in this package, and it does not make sense to make `Create` fallback. The semantics of `Create` are that it opens the file in `O_RDWR`, if we—instead—fallback to opening up the file in `O_WRONLY`, then we violate that contract.

Beyond that point, if we are working on such a fallback inside this package, there would be no need for any type conversion, because we can test against `ssh_FX_OP_UNSUPPORTED` which is an untyped numeric constant. Thus, it can be tested against any numeric value.

It is only outside of the package that this concern becomes relevant, because `ssh_FX_OP_UNSUPPORTED` is unexported, so the only available access to that value is with `ErrSshFxOpUnsupported` which is type `fxerr`.

**Comment by eikenb** [comment]
The reThe documentation fix is simple and obvious.

The StatusError.Code, ErrSshFxOpUnsupported type mismatch is probably best fixed by convertint StatusError.Code into an fxerr type. This is borderline API breaking though, so I'm not 100% how it plays with SemVer. This change could break someones code though, which I'm not a big fan of.

There are 2 workarounds I can think. 
1. Add a method StatusError.FxCode() that returns the Code coverted to fxerr
2. Make fxerr public (FxErr) to make manual type conversions possible.

Anyone (@rama3i, @sugacube, @puellanivis) have a preference or another option?

**Comment by rama3i** [comment]
IMO, I would go with what @puellanivis mentioned, which is also on your first point. Making a new method on StatusError would be a better option as it introduce less intrusion on existing code. I would vote for option 1

**Comment by puellanivis** [comment]
Adding an `FxCode()` receiver method also means one can type-assert against an interface, instead of type-asserting to a type. Although some difficulty comes in that `fxerr` implements `error` so it’s a little weird.

But in the end the `FxCode()` provides the best forward-compatibility, i.e. the returned value can be used with implied types, and thus code need not worry about what the specific type of the value being returned is, as this library need only ensure that it is comparable to the `ErrSshFxOpUnsupported` type.

I definitely vote for Option 1.

**Comment by sugacube** [comment]
Agree breaking api is to be avoided. I'm not sure which option is best, maybe preference for exporting error codes. But as I'm not affected, i'll leave it up to you.

Maybe worth looking at impact of new go1.13 error wrapping? This may become more standard in the future, maybe choose the option that is easiest to transition to go1.13 error wrapping in the future?

On a side note, i'm not sure if this deserves this much attention/discussion as imho this AWS thing is a minor issue (but certainly @eikenb thanks for involving users before making changes)

**Comment by puellanivis** [comment]
Beyond eventually adding an `Unwrap` that would return the `fxerr` (since it is an `error` type itself), then using the new `errors.Is(err, ErrSshFxOpUnsupported)` comes pretty much free. Alternatively, it could also implement the `Is(error)` interface and return `true` if the given `sftp.Err…` and the underlying `fxerr.Code` match…

**Comment by eikenb** [comment]
Made time today to get this done. Pushed PR #310 to address both the documentation part and FxCode error part.
