### ISSUE TITLE
SFTP access blocked and eat too many memory when received message too long

### ISSUE THREAD

**Issue by wutz** [pkg/sftp#308]
First set some output, like `echo abc`, under the access user's `.bashrc`, then using sftp to access that user will reproduce the problem.

Go pprof:

```sh
ROUTINE ======================== github.com/pkg/sftp.recvPacket in /Users/wutz/.go/path/pkg/mod/github.com/pkg/sftp@v1.10.1/packet.go
    1.52GB     1.52GB (flat, cum) 99.94% of Total
         .          .    141:	var b = []byte{0, 0, 0, 0}
         .          .    142:	if _, err := io.ReadFull(r, b); err != nil {
         .          .    143:		return 0, nil, err
         .          .    144:	}
         .          .    145:	l, _ := unmarshalUint32(b)
    1.52GB     1.52GB    146:	b = make([]byte, l)
         .          .    147:	if _, err := io.ReadFull(r, b); err != nil {
         .          .    148:		debug("recv packet %d bytes: err %v", l, err)
         .          .    149:		return 0, nil, err
         .          .    150:	}
         .          .    151:	if debugDumpRxPacketBytes {
```

In the openssh project, sftp-client will be check received message whether greater than SFTP_MAX_MSG_LENGTH (256 * 1024 )

> https://github.com/openssh/openssh-portable/blob/master/sftp-client.c#L154-L158

**Comment by gaurav1068** [comment]
@eikenb: any plans to get this reported as CVE? We happened to use this in production & hit this issue when we were doing the following test in a memory constrained environment.
Steps to do repro:
Created AWS CentOS Linux release 7.5.1804 (Core) with login as root user disabled 
another user centos with valid public key is able to do ssh
when using public key of centos and username as root
we faced the same issue.

**Comment by eikenb** [comment]
I hadn't thought of filing a CVE for this... I guess I tend to associate that with larger projects and that if anything needing a CVE bubbled up to an upstream app that they'd just file it at their level.

That said, I could look into it. Though I'm curious what benefit it would provide to the community? Are you putting together a CVE for your project and would benefit from having it as a reference?

Assuming I look into it, looks like I would file it under the general Mitre Open Source CNA as an other/remote/denial-of-service type.

**Comment by gaurav1068** [comment]
> Though I'm curious what benefit it would provide to the community?

Doing a repro is easy, any centos vm with login as root disabled and using the key of alternate user will do a repro of this behaviour.
> Are you putting together a CVE for your project and would benefit from having it as a reference?

Not necessary, we have documented this in our internal product wiki.

> Assuming I look into it, looks like I would file it under the general Mitre Open Source CNA as an other/remote/denial-of-service type.

👍

**Comment by srinathgs** [comment]
@eikenb : The rationale we (@gaurav1068 & me) had was that there would be many users of this library & by logging a CVE, it would notify the community that there is a denial of service attack vector on all users of this library. 

If the memory allocated was of the order of few KBs, it would have been inconspicuous. But, given that this is 1.5GB allocation where the service that uses this library's regular memory consumption is around 30~50MB, it was fairly noticeable. In cases where we enabled memory limits on the docker container where this service is running, it resulted in `fatal error: runtime: out of memory`.

When we hit this issue, the first thing we did was to check all [CVEs with the SSH keyword](https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=SSH). Hence, we thought it would be a good idea to log a CVE & so that folks hitting this issue can benefit from this & upgrade to a version >=1.11.0
