### ISSUE TITLE
How can I control the size of sftp every read or write?

### ISSUE THREAD

**Issue by xiejunshi** [pkg/sftp#318]
![image](https://user-images.githubusercontent.com/37329665/68112643-bc0b1e80-ff2c-11e9-9b86-2b43eac84b24.png)
![image](https://user-images.githubusercontent.com/37329665/68112756-0db3a900-ff2d-11e9-9838-c88459e60fb1.png)

1、I printed the log in this place and found that the size of each write file is 32k. I want to increase the size of each write to the server.what should I do?

![image](https://user-images.githubusercontent.com/37329665/68113019-b82bcc00-ff2d-11e9-9dae-6910e486cfc3.png)

2、Is this way of writing concurrent? because I found that the second write is less length.

**Comment by puellanivis** [comment]
I’m unsure as to where exactly it is being called, but [`io.Copy` uses a 32KiB buffer](https://golang.org/src/io/io.go?s=12796:12856#L391) which is likely why it is doing a `32k` capacity write every time, but it’s not actually getting the full 32768 bytes from the source, which is why it is somewhat less than 32k.

There’s any number of reasons. Yes, with `WriteAt` the calls could be being made concurrently. Perhaps also log out the `off` value for interesting data on that as well.

**Comment by xiejunshi** [comment]
Thank you for your answer.
And I have another question:
How can I tell if the file has been written?

**Comment by xiejunshi** [comment]
Thank you for your answer.
And I have another question:
How can I know if a file has been written?
