### ISSUE TITLE
How can I know if a remote file is hidden or not ?

### ISSUE THREAD

**Issue by vincenthcui** [pkg/sftp#349]
I can judge by "." prefix on linux server, but how can I do so on Windows?

**Comment by eikenb** [comment]
Warning: I don't use windows and am definitely not an expert. This info is from a few minutes of online searching/research.

Windows seems to use file attributes to set files as hidden. You could look into what Go reports back for with file info to see if there is anything there that can be of use. I found a  resources on how to make hidden files with Go on windows, maybe it will help give a clue about what to do.

https://stackoverflow.com/questions/54139606/how-to-create-a-hidden-file-in-windows-mac-linux

**Comment by vincenthcui** [comment]
thanks for your generous help @eikenb. I have tried the way stackoverflow offered, however it works on windows local machine, but can not work on sftp remote server. I think it may be a design flow for sftp server or sftp protocol, and I will do further research for this situation.

**Comment by puellanivis** [comment]
I think a central problem here is that the only file attributes recognized by SFTP definitions are POSIX attributes, that do not include a “hidden” flag like Windows does. As such, there’s no real way to set this flag in a POSIX manner, which because of how SFTP is designed, everything is automatically squeezed through.

Anything supporting setting a hidden attribute on a Windows SFTP server endpoint is likely non-standard, or an extension.
