### ISSUE TITLE
Can't remove directories on a Serv-U server

### ISSUE THREAD

**Issue by gwatts** [pkg/sftp#35]
Commit e8b14451d6c62d63aa3d5dab67fcbd11e7740381 merged RemoveDirectory() into the general Remove() call and tries to be smart by attempting an RMDIR call if REMOVE fails with an a FAILURE code.

This works ok for compliant servers, but Serv-U returns 0x18 when issuing a REMOVE call on a directory and Remove() fails as a result.

I'm not sure it really makes sense to merge RemoveFile and RemoveDirectory into one call anyway; it doesn't match the underlying protocol - Could we consider reversing that?  Or at least adding an explicit RemoveDirectory() call if backwards compatibility is a concern.

**Comment by davecheney** [comment]
@claudiofelber thoughts?

**Comment by claudiofelber** [comment]
I merged `RemoveDirectory()` into `Remove()` to be compatible with the standard Go function names in the os package ([os.Remove()](https://golang.org/pkg/os/#Remove) addresses both files and directories). This allows for easy duck typing and is, in my opinion, one of the key strengths of Go.

On the other hand merging the two functions resulted in a slight performance decrease because Remove(), not knowing whether it is dealing with a file or a directory, first tries to treat the specified path as a file and, if that fails, as a directory:
https://github.com/pkg/sftp/blob/506297c9013d2893d5c5daaa9155e7333a1c58de/client.go#L431

We could make the internally used `removeDirectory()` function public. This might fix the problem with Serv-U, would speed up deletion of directories a little bit and still remain compatible with the standard Go naming scheme. As a drawback it will clutter the API.

The other possibility would be to alter the error handling in `Remove()` to detect the non-standard response of the Serv-U server.
@gwatts: When you write that Serv-U returns 0x18 for a SSH_FXP_REMOVE on a directory, do you mean it returns 0x18 in the status code? As far as I know the specification only defines the following status codes:

```
#define SSH_FX_OK                            0
#define SSH_FX_EOF                           1
#define SSH_FX_NO_SUCH_FILE                  2
#define SSH_FX_PERMISSION_DENIED             3
#define SSH_FX_FAILURE                       4
#define SSH_FX_BAD_MESSAGE                   5
#define SSH_FX_NO_CONNECTION                 6
#define SSH_FX_CONNECTION_LOST               7
#define SSH_FX_OP_UNSUPPORTED                8
```

**Comment by gwatts** [comment]
@claudiofelber Correct - It returns 0x18/24 as the status code - I'm sure the server is not compliant with the spec, but unfortunately it's not under my control.  Removing regular files works ok (as does every other operation i've tried with it).

fwiw I very much like that the api matches the Go library naming wherever possible, but seems like there should be some way of explicitly calling RemoveDirectory or RemoveFile (the Go library would let me call syscall.Rmdir, for example, if that's really what I wanted).

In any case, perhaps the code here could just for SSH_FX_FAILURE or a code >= SSH_FX_UNKNOWN (assuming it were defined to be 9) and retry then?

Here's my little test program for reference:

````go
package main

import (
        "fmt"
        "os"

        "github.com/pkg/sftp"
        "golang.org/x/crypto/ssh"
)

func main() {
        if len(os.Args) != 5 {
                fmt.Println("Usage: sftp-test <host> <username> <password> <file-to-remove>")
                os.Exit(100)
        }

        host, username, password, fn := os.Args[1], os.Args[2], os.Args[3], os.Args[4]

        sshClient, err := ssh.Dial("tcp", host, &ssh.ClientConfig{
                User: username,
                Auth: []ssh.AuthMethod{
                        ssh.Password(password),
                },
        })

        if err != nil {
                fmt.Println("ssh connect failed: ", err)
                os.Exit(100)
        }

        sftpClient, err := sftp.NewClient(sshClient)
        if err != nil {
                fmt.Println("sftp new client failed: ", err)
                os.Exit(100)
        }

        if err := sftpClient.Remove(fn); err != nil {
                if status, ok := err.(*sftp.StatusError); ok {
                        fmt.Printf("Remove failed with SFTP StatusError code=%d  error=%s\n", status.Code, status)
                } else {
                        fmt.Println("Remove failed with unknown error: ", err)
                }
        } else {
                fmt.Println("Remove OK")
        }
}
````

And the output from it:

````
[gareth@Dibbley ~]$ go run ~/sftp-test.go hostname:22 username password GarethDir
Remove failedwith SFTP StatusError code=24  error=sftp: "Specified file is a directory." (unknown)
[gareth@Dibbley ~]$ 
[gareth@Dibbley ~]$ go run ~/sftp-test.go hostname:22 username password GarethFile
Remove OK
````

**Comment by xiu** [comment]
Hi, I have the same issue. This status code seems to be specified in the latests draft (starting with draft-07) of the protocol, see http://tools.ietf.org/html/draft-ietf-secsh-filexfer-13

**Comment by xiu** [comment]
@davecheney I've made the modifications in https://github.com/xiu/sftp, would that be sufficient for you to merge?

**Comment by davecheney** [comment]
@xui, sure, send a PR and we can talk about it.
