### ISSUE TITLE
Error“internal inconsistency” in downloading file from special sftp server(openssh 8.3)

### ISSUE THREAD

**Issue by dongdatangjie** [pkg/sftp#403]
when I use github.com/pkg/sftp ,I find download file error internal inconsistency,if my file less than 32*1024,I find this file has downloaded,but in file,more than 1byte  in the end.openssh 8.3 will send message include head and data ,if head tell us the length is 1021,but data has 1022, openssh client will task data by length,but go sftp client get all data

case sshFxpData:
	l, data := unmarshalUint32(data)
	if req.offset == writeOffset {
		nbytes, err := w.Write(data[:l])
		copied += int64(nbytes)
		if err != nil {
			// We will never receive another DATA with offset==writeOffset, so
			// the loop will drain inFlight and then exit.
			firstErr = offsetErr{offset: req.offset + uint64(nbytes), err: err}
			break
		}
		if nbytes < int(l) {
			firstErr = offsetErr{offset: req.offset + uint64(nbytes), err: io.ErrShortWrite}
			break
		}
		switch {
		case offset > fileSize:
			desiredInFlight = 1
		case desiredInFlight < f.c.maxConcurrentRequests:
			desiredInFlight++
		}
		writeOffset += uint64(nbytes)
		for {
			pendingData, ok := pendingWrites[writeOffset]
			if !ok {
				break
			}
			// Give go a chance to free the memory.
			delete(pendingWrites, writeOffset)
			nbytes, err := w.Write(pendingData)
			// Do not move writeOffset on error so subsequent iterations won't trigger
			// any writes.
			if err != nil {
				firstErr = offsetErr{offset: writeOffset + uint64(nbytes), err: err}
				break
			}
			if nbytes < len(pendingData) {
				firstErr = offsetErr{offset: writeOffset + uint64(nbytes), err: io.ErrShortWrite}
				break
			}
			writeOffset += uint64(nbytes)
		}
	}

I think this code should change like this w.Write(data[:l]), than everything is ok, we can download file without problem.
please modify source code and we will upgrade our project,thank you.

**Comment by puellanivis** [comment]
🤔 I think you might be right, but I’m not sure about what cases can occur where there should be any follow on bytes in an SSH_FXP_DATA packet. Such a packet should by standards be: request ID uint32, then a string of data. (a length+data). Nothing else.

However, if this is right, then there are a few more changes that would need to be made as well, since we would not be able to assume that the package is strictly conforming to the draft standard that we are working from, but might contain additional data.

I’ve already been working on rewriting this client code. Especially to account for these small-file implementations. (If we only expect one remote read (or two to get an io.EOF) then there‘s not really a good reason do a whole complicated in parallel request scheme.)

**Comment by dongdatangjie** [comment]
can you modify code first,and we can reuse you opensource code continue .Thank you!

**Comment by puellanivis** [comment]
We likely will not be able to make the change and cut a new version, and then cut a new version after I have finished the client changes from the `more-optimization` PR.

Unfortunately, I have been very busy taking care of loose threads before the holidays at my day job, and so I haven’t been able to finish my work there.

It will come, and perhaps even before the end of the year, but not by End of Week, yet.

**Comment by dongdatangjie** [comment]
thank you
