### ISSUE TITLE
site exec

### ISSUE THREAD

**Issue by fdefilippo** [pkg/sftp#453]
hi, I would like to implement some kind of site exec so that I can execute a command like below:

exec /path/to/myprogram args

is there any example from which to draw inspiration?

thank you.

**Comment by puellanivis** [comment]
As far as I am aware the SFTP protocol offers no such functionality.

Since packets are bundled into discrete function packets, and we are not simply exchanging text commands, there is not really a way to do this sort of thing without using some special `SSH_FXP_EXTENDED` packets, and as of now, we have no way to support custom extended packets.

**Comment by drakkan** [comment]
@fdefilippo this can be easily done using the SSH protocol.

You can add an handler for the `exec` req.Type [here](https://github.com/pkg/sftp/blob/master/examples/request-server/main.go#L111) for example.

**Comment by fdefilippo** [comment]
Thank you.

**Comment by drakkan** [comment]
@fdefilippo the above answer is to handle commands server side (within a Go SSH server). If you want to execute a command from a Go client application to a generic SSH server you can use something like [this](https://github.com/drakkan/sftpgo/blob/main/sftpd/sftpd_test.go#L9258)
