### ISSUE TITLE
Change current working directory?

### ISSUE THREAD

**Issue by a-urth** [pkg/sftp#552]
Am I missing something or there is no way to change working directory? If so then why?

Its possible to implement it on a client side of course but it just brings what is looks like unnecessary complication.

**Comment by puellanivis** [comment]
SFTP does not really itself have any concept of a working directory. The working directory that you see in `sftp` clients is always—as you call it—a client side implementation.

We chose to keep a closer adherence to SFTP itself, rather than adding a working directory concept ourselves in our abstraction level.

**Comment by a-urth** [comment]
Makes sense. Thank you for answering!On 2 Jul 2023, at 13:58, Cassondra Foesch ***@***.***> wrote:﻿
SFTP does not really itself have any concept of a working directory. The working directory that you see in sftp clients is always—as you call it—a client side implementation.
We chose to keep a closer adherence to SFTP itself, rather than adding a working directory concept ourselves in our abstraction level.
