### ISSUE TITLE
Support for changing access and modification times (atime/mtime) on symbolic links (Lutimes) missing

### ISSUE THREAD

**Issue by NikitaCOEUR** [pkg/sftp#594]
## Description
It seems that the current implementation does not support changing access time (atime) and modification time (mtime) for symbolic links. On Unix systems, the lutimes command is typically used to update these timestamps for symlinks without following them. Currently, the library allows timestamp changes for regular files, but it appears that symbolic links are not handled similarly.

This functionality is particularly useful for tools and processes that need to preserve timestamps on symlinks, such as backup utilities or filesystem synchronization tools.

I'm trying to implement symlink handling for the SFTP backend of the rclone tool.
Currently, we use `Chtimes` to modify this information, but it never changes anything on symlinks. 

## Expected Behavior:

    A method should be implemented that allows users to update the atime and mtime for symbolic links directly, without dereferencing the link.
    This could be achieved by integrating a lutimes-like function on Unix-based systems.

## Steps to Reproduce:

    Attempt to update the atime or mtime of a symbolic link using the current SFTP library.
    Observe that the timestamps are not modified.

I haven't seen any information regarding your stance on this issue, which is why I wanted to open this ticket for discussion. I need to know if I should manage timestamps for symlinks in the rclone SFTP backend. I'm currently testing this with SFTPGo as the backend.

**Comment by puellanivis** [comment]
Unfortunately, we’re limited to what is offered by the SFTP standard, and only up to [Version 3](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02). This unfortunately does not have any version of `lutimes`, or for operating an `SSH_FXP_SETSTAT` on the symlink rather than its target, (or for opening the symlink as a file descriptor itself, which would allow an `SSH_FXP_FSETSTAT`.

Even if we implemented this feature ourselves, this would only solve the problem within our package, and would be standards uncompliant, or it would be an `SSH_FXP_EXTENDED` that wouldn’t be supported by any other server implementation, so you would just get `SSH_FX_OP_UNSUPPORTED` at best.

The workarounds I find for setting these times for other clients, are working around this by executing a remote command to perform the operation, but such an operation would be outside of the scope of this package.

**Comment by NikitaCOEUR** [comment]
Thank you very much for the detailed explanation. This answers my question. I will close this ticket now.
