### ISSUE TITLE
Context support for all client methods

### ISSUE THREAD

**Issue by mappu** [pkg/sftp#606]
Context support is available since #222, but only at a raw request level, not for all the sftp.Client methods.

It should be possible to call all methods (e.g. Lstat, Remove, Open, Rename, Chmod) with a context parameter. 

This was already implemented for ReadDir (ReadDirContext) between v0.12 and v0.13, but, it should be available widely.

**Comment by puellanivis** [comment]
Small pedantic note: I think you’ve misread things. #222 provided contexts for the server side request handling. You’ll see in the branch `dev-v2` that this context principle has been extended properly and fully into the `ServerHandler` taking context arguments. The client support for contexts and `ReadDirContext` came in an entirely different and much later PR: #565. These two topics are quite different, the server and client code are significantly different and “incompatible.”

However, nothing is actually wrong with your argument, so let me address that now: indeed, we could potentially provide all client functions with contexts, but most of them are not at all long-running, and thus would not significantly benefit from the ability to cancel them. That is, Lstat consists of a single packet sent, and a single packet received, also for Remove, Open, Rename, and Chmod. As such, there’s essentially no difference between canceling the context, and just waiting for the reply.

In fact, ignoring the reply isn’t particularly useful anyways, because once the request has been sent, the server will attempt to perform the action, whether we’ve given up waiting on the request or not. There is no way to trigger a cancelation of the request out to the service. So, a context cancelation becomes a dangerous client desync with the server: the client thinks an error was returned, but the server performed the action and sent back a status ok already. In fact, for `Open` even more so, this would allocate a handle and file descriptor on the server, with no `Close` to accompany it, so memory and file descriptor leakage.

Now, similar to ReadDir, where it could potentially be long-running, ReadFrom and WriteTo could potentially benefit from a parent context the same as ReadDir, but here we’re also constrained to existing interfaces that do not contain contexts in the arguments. Providing a ReadFromContext and WriteToContext would potentially have some utility though, for example, if you’re trying to read from `/dev/zero` and want to stop reading after some period of time. But these would also need special handling of the context so that if it sent a write request, that it waits for the answer to that write… the only safe responses to throw away are after all reads, where a desync between client and server about how much data was read is effectively irrelevant… since, the client sends a read offset with every request, reads are essentially stateless on the server side.

As well, we would need to consider API noise pollution. Having doubles of every function with a context and without a context would quickly make the godoc significantly less useful, and double the methods that need to be sifted through to identify the one you want to use, and then present a question of “wait, do I want the one with a context or not?” Choice fatigue is a real thing, and as noted, one of those operations is inherently dangerous… so if people default to picking the context version every time, we would be building less and less safe code.

**Comment by mappu** [comment]
Thank you for the detailed update.

My focus is on large storage servers where HDD space is provisioned for many high-traffic users. In this case, the SFTP server is intermittently unresponsive whenever it blocks on disk i/o queue. Even a short command can hang the client app indefinitely waiting for a network response.

I don't see any solution for this other than adding context support to the client methods, is any other idea possible?

Regarding write requests, the inconsistency arises naturally from CAP theorem in any networked system. In my case I have a solution at the application level and don't need to rely on consistency at the SFTP server side, but I can see this being an issue for others. Perhaps if context support is added, these methods could have a warning.

**Comment by puellanivis** [comment]
I still take the position that the correct way to handle mutable operations having already been sent to the service, is to wait on the response, and have the caller decide the appropriate response. Of note, even if the context is cancelled during a `Client.ReadDir()`, the close handle packat is still sent, and waited for with the `context.Background()` context.

CAP theory proposes that only two of Consistency, Availability, or Partition tolerance are possible, not that consistency between server and client is impossible. In fact, the SFTP protocol does guarantee consistency, and rather instead does not guarantee partition tolerance, and this particular “sometimes there’s an unresponsive service, and requests fail to receive responses” is directly a result of this partition intolerance.

You have found a deficiency of the SFTP protocol: partition intolerance means the system ceases to operate, or degrades operations in the face of messages being dropped or delayed. Yes, indeed it does. And this package reflects that same intolerance, and the appropriate place to deal with that failure is as you have done, in the application layer. Where you can decide to back out, reconnect, and reestablish what state the remote service is in. SFTP provides no way in the protocol to do this.
