### ISSUE TITLE
Proposal: improve flexibility of Server type

### ISSUE THREAD

**Issue by mdlayher** [pkg/sftp#66]
I've been mulling over a few ideas to make the `Server` type a bit more flexible.  I'd like to use a SFTP server in a project I'm doing, but unfortunately, it provides no transparency as to what the server is actually doing.

1) A simple approach would be to create a `Filesystem` interface for calls such as creating, reading, or writing a file, and making the default implementation use the `os` calls.  This would provide flexibility to perform SFTP operations on top of any arbitrary `Filesystem`.

```go
type Filesystem interface {
    Open(path string) (file *os.File, err error)
    Close() error
    // etc...
}
```

2) Another idea would be to add "callback" functions for some of the SFTP server's actions.  If non-nil, the callback would be invoked whenever the action was performed.

```go
s := &sftp.Server{
    OnOpen: func(path string) {
        log.Println("opened file:", path)
    },
}
```

3) Finally, perhaps it would be feasible to provide a similar interface to `net/http`, so that arbitrary `sftp.Handler` functions can be created to handle various request types.

```go
type Handler struct {}

func (h *Handler) ServeSFTP(w sftp.Responder, r *sftp.Request) {
    log.Println("request:", r.Type)
    _, _ = sftp.PermissionDenied(w)
}

func main() {
    s := &sftp.Server{
        Handler: &Handler{},
    }

    _ = s.Serve()
}
```

I imagine that #1 and/or #3 would probably be the best ideas, and the most idiomatic as well.  What do you think, @davecheney ?  I'd be happy to try to spike out some pull requests if you're interested.  Thanks for your time.

**Comment by xor-gate** [comment]
IMO idea 3 is very nice because it maps 1:1 on the interface of the `net/http` handler and is very easy to use. Specially when integrating into a application.

**Comment by mdlayher** [comment]
I definitely agree, though it would require a lot of thought to make a nice API.  Are we concerned with changing the API of this package?  If not, I'm happy to do some hacking on a prototype.

**Comment by xor-gate** [comment]
I think this should done in a separate branch for discussion. Probably it should be done for both client and server implementations (same as `net/http` provides). As far as I know he `github.com/pkg/sftp` is the only sftp implementation for golang which is used by 25 other opensource projects (https://godoc.org/github.com/pkg/sftp?importers). It would be nice to also have other projects and peoples opinions when you start hacking @mdlayher  :+1:. So you precious time wont be wasted and thrown away.

**Comment by marksheahan** [comment]
FWIW I had something similar to 1) when working on the server package. The
two backends were the os package, and the sftp client (meaning server
Open() connects to 2nd client Open(), etc). I needed a wrapper layer around
both the filesystem, and individual files: Open() and other file ops could
handle an *os.File backend as well as an *sftp.File backend.

The code turned out ugly this way and was soon abandoned in favor of a
simple direct coupling to os package calls. In retrospect, wrapping the
filesystem backend is what created mess there, and was the wrong point to
create wrappers. It would have been better to wrap the packet responders
instead of the filesystem.

I would recommend something like approach 2 listed above, an interface of
handlers for each packet type. Something like:
1) remove the serverRespondablePacket interface
2) create a set of callbacks, one for each packet type:
type SftpServerFuncsRenameMe interface {
    RespondOpenPacket(pkt sshFxpOpenPacket) error
    RespondReadPacket(pkt sshFxpReadPacket) error
.... etc
}

This kind of implementation would allow any arbitrary backend you can dream
up, without needing to wrap os.File in most cases. It would also allow
multiple sftp protocol versions from one codebase, because you can just
substitute implementations depending on the negotiated protocol version.


On Thu, Dec 31, 2015 at 9:29 AM, Jerry Jacobs <notifications@github.com>
wrote:
>
> I think this should done in a separate branch for discussion. Probably it
should be done for both client and server implementations (same as net/http
provides). As far as I know he github.com/pkg/sftp is the only sftp
implementation for golang which is used by 25 other opensource projects (
https://godoc.org/github.com/pkg/sftp?importers). It would be nice to also
have other projects and peoples opinions when you start hacking @mdlayher .
So you precious time wont be wasted and thrown away.

**Comment by PunKeel** [comment]
Would love it, too ! :+1: (no matter which one)

**Comment by mdlayher** [comment]
I've submitted some cleanup PRs to reduce duplication a bit and make it easier to refactor the server.  I plan on starting a branch with design 3 (`net/http`-like API) in the coming days.

@PunKeel that is exactly what I would like as well.  Being able to front any kind of data stream with SFTP would be quite handy.

**Comment by xor-gate** [comment]
@mdlayher maybe for the new callback-like interface would be nice to have some sort of option to "chroot/restrict", a user or ssh key into a "path" ?

**Comment by mdlayher** [comment]
@xor-gate Yep, that is certainly a feature I would like.  I was thinking about mimicking the `net/http.FileServer` way of doing things.

Something along these lines:

```go
func ServeSFTP(w sftp.Responder, r *sftp.Request) {
    if !authenticated(r) {
        sftp.FileServer(sftp.Dir("/srv/sftpchroot/"))
        return
    }

    sftp.FileServer(sftp.Dir("/"))
}
```

**Comment by xor-gate** [comment]
Thats kind of awesome and follows the go idiomatic style, and is very convenient to read :+1:

**Comment by xor-gate** [comment]
So the key fingerprint and/or the user is passed along with the sftp.Request, as per http.Request it contains the `Remote string`golang?

**Comment by mdlayher** [comment]
Yep, most likely.  I haven't actually started a branch yet, but that is what I'm envisioning.

**Comment by xor-gate** [comment]
Maybe it is an idea to update the first comment in this thread/issue with a todolist which is automaticly tracked by github. Like this: https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments
Then people could see what needs to be done and what is already done. And exchange some ideas.

**Comment by mdlayher** [comment]
I'll make a new issue now, @xor-gate !
